### PR TITLE
Add questions app

### PR DESCRIPTION
**Pull request by kevinetienne**

### CODE REVIEW

**Comment by KevinEtienne** [comment]
@meshy can you review please?

**Comment by meshy** [comment]
Looks good so far. Should we add the users FKs yet?

**Comment by KevinEtienne** [comment]
Oh yeah, I've rebase this branch for that, thanks

**Comment by meshy** [comment]
:+1:

**Comment by KevinEtienne** [comment]
Thanks updated

**Comment by kevinetienne** [comment]
haha :)

**Pull request merged**
